---
version: "2"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 6

  complex-logic:
    enabled: true
    config:
      threshold: 5

  file-lines:
    enabled: true
    config:
      threshold: 250

  method-complexity:
    enabled: true
    config:
      threshold: 25

  method-count:
    enabled: true
    config:
      threshold: 20

  method-lines:
    enabled: true
    config:
      threshold: 50

  nested-control-flow:
    enabled: true
    config:
      threshold: 6

  return-statements:
    enabled: true
    config:
      threshold: 10

  identical-code:
    enabled: true
    config:
      threshold: 65

  similar-code:
    enabled: true
    config:
      threshold: 85

exclude_patterns:
  - "**/umd/*.ts"
  - "**/*.config.js"
  - "**/*.test.ts"
  - "**/*.md"
